global.author = "HxcoderID";
global.key_free = ["HxcoderID"];
global.key_premium = ["HxcoderID130701"];
global.limit_free = "30";
global.limit_premium = "99999";
global.mongo_Db = "mongodb+srv://hendraxd:hFPdksuMrRxugncf@hendraxd.oamahep.mongodb.net/?retryWrites=true&w=majority";
global.recaptcha_key_1 = "6LdPjp0nAAAAACJ_oFFvYFy3XCdAlJ5xXoHznsue";
global.recaptcha_key_2 = "6LdPjp0nAAAAAA-IuS8hH3tZrnoKn3V7KgFEOhMt";
global.my_email = "hgindonesia3@gmail.com";
global.my_email_password = "ufbdqtihvtitilqa";
global.activation_token = "-@Pqnap+@(/1jAPPnew/@10";
global.port = 8080
